=== CERTCC/SSVC/data/schema/v2/DecisionPoint_2_0_0.schema.json
{
  "title": "DecisionPoint",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://certcc.github.io/SSVC/data/schema/v2/DecisionPoint_2_0_0.schema.json",
  "description": "This schema defines the structure to represent an SSVC DecisionPoint object.",
  "type": "object",
  "$defs": {
    "DecisionPointValue": {
      "title": "DecisionPointValue",
      "description": "Models a single value option for a decision point.\n\nEach value should have the following attributes:\n\n- name (str): A name\n- description (str): A description\n- key (str): A key (a short, unique string) that can be used to identify the value in a shorthand way\n- _comment (str): An optional comment that will be included in the object.",
      "properties": {
        "key": {
          "title": "Key",
          "description": "A short, non-empty string identifier for the object. Keys must start with an alphanumeric, contain only alphanumerics and `_`, and end with an alphanumeric.(`T*` is explicitly grandfathered in as a valid key, but should not be used for new objects.)",
          "examples": [
            "E",
            "A",
            "SI",
            "L",
            "M",
            "H",
            "Mixed_case_OK",
            "alph4num3ric"
          ],
          "minLength": 1,
          "pattern": "^(([a-zA-Z0-9])|([a-zA-Z0-9][a-zA-Z0-9_]*[a-zA-Z0-9])|(T\\*))$",
          "type": "string"
        },
        "name": {
          "title": "Name",
          "minLength": 1,
          "type": "string"
        },
        "definition": {
          "title": "Definition",
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "key",
        "name",
        "definition"
      ],
      "type": "object"
    }
  },
  "properties": {
    "namespace": {
      "title": "Namespace",
      "description": "The namespace of the SSVC object.",
      "examples": [
        "ssvc",
        "cisa",
        "x_example.test#test//.example.test#private-extension",
        "ssvc/de-DE/.example.organization#reference-arch-1"
      ],
      "maxLength": 1000,
      "minLength": 3,
      "pattern": "^(x_([a-z]|[0-9])(((([a-z]|[0-9])|-)){0,61}([a-z]|[0-9]))?(\\.([a-z]|[0-9])(((([a-z]|[0-9])|-)){0,61}([a-z]|[0-9]))?)+#(([a-z]|[0-9]))+((\\.|-)(([a-z]|[0-9]))+)*|[a-z]([a-z]|[0-9])(((\\.|-))?(([a-z]|[0-9]))+)+(#(([a-z]|[0-9]))+((\\.|-)(([a-z]|[0-9]))+)*)?)((/(([a-zA-Z]{2,3}(-[a-zA-Z]{3}(-[a-zA-Z]{3}){0,2})?|[a-zA-Z]{4,8})(-[a-zA-Z]{4})?(-([a-zA-Z]{2}|[0-9]{3}))?(-(([a-zA-Z0-9]){5,8}|[0-9]([a-zA-Z0-9]){3}))*(-[0-9A-WY-Za-wy-z](-([a-zA-Z0-9]){2,8})+)*(-[xX](-([a-zA-Z0-9]){2,8})+)?|[xX](-([a-zA-Z0-9]){2,8})+|i-default|i-mingo)(/((([a-zA-Z]{2,3}(-[a-zA-Z]{3}(-[a-zA-Z]{3}){0,2})?|[a-zA-Z]{4,8})(-[a-zA-Z]{4})?(-([a-zA-Z]{2}|[0-9]{3}))?(-(([a-zA-Z0-9]){5,8}|[0-9]([a-zA-Z0-9]){3}))*(-[0-9A-WY-Za-wy-z](-([a-zA-Z0-9]){2,8})+)*(-[xX](-([a-zA-Z0-9]){2,8})+)?|[xX](-([a-zA-Z0-9]){2,8})+|i-default|i-mingo)|\\.([a-z]|[0-9])(((([a-z]|[0-9])|-)){0,61}([a-z]|[0-9]))?(\\.([a-z]|[0-9])(((([a-z]|[0-9])|-)){0,61}([a-z]|[0-9]))?)+#(([a-z]|[0-9]))+((\\.|-)(([a-z]|[0-9]))+)*|\\.(([a-z]|[0-9])(((([a-z]|[0-9])|-)){0,61}([a-z]|[0-9]))?(\\.([a-z]|[0-9])(((([a-z]|[0-9])|-)){0,61}([a-z]|[0-9]))?)+|([a-z]|[0-9])(((([a-z]|[0-9])|-)){0,61}([a-z]|[0-9]))?(\\.([a-z]|[0-9])(((([a-z]|[0-9])|-)){0,61}([a-z]|[0-9]))?)+#(([a-z]|[0-9]))+((\\.|-)(([a-z]|[0-9]))+)*)\\$(([a-zA-Z]{2,3}(-[a-zA-Z]{3}(-[a-zA-Z]{3}){0,2})?|[a-zA-Z]{4,8})(-[a-zA-Z]{4})?(-([a-zA-Z]{2}|[0-9]{3}))?(-(([a-zA-Z0-9]){5,8}|[0-9]([a-zA-Z0-9]){3}))*(-[0-9A-WY-Za-wy-z](-([a-zA-Z0-9]){2,8})+)*(-[xX](-([a-zA-Z0-9]){2,8})+)?|[xX](-([a-zA-Z0-9]){2,8})+|i-default|i-mingo)))*|/(/((([a-zA-Z]{2,3}(-[a-zA-Z]{3}(-[a-zA-Z]{3}){0,2})?|[a-zA-Z]{4,8})(-[a-zA-Z]{4})?(-([a-zA-Z]{2}|[0-9]{3}))?(-(([a-zA-Z0-9]){5,8}|[0-9]([a-zA-Z0-9]){3}))*(-[0-9A-WY-Za-wy-z](-([a-zA-Z0-9]){2,8})+)*(-[xX](-([a-zA-Z0-9]){2,8})+)?|[xX](-([a-zA-Z0-9]){2,8})+|i-default|i-mingo)|\\.([a-z]|[0-9])(((([a-z]|[0-9])|-)){0,61}([a-z]|[0-9]))?(\\.([a-z]|[0-9])(((([a-z]|[0-9])|-)){0,61}([a-z]|[0-9]))?)+#(([a-z]|[0-9]))+((\\.|-)(([a-z]|[0-9]))+)*|\\.(([a-z]|[0-9])(((([a-z]|[0-9])|-)){0,61}([a-z]|[0-9]))?(\\.([a-z]|[0-9])(((([a-z]|[0-9])|-)){0,61}([a-z]|[0-9]))?)+|([a-z]|[0-9])(((([a-z]|[0-9])|-)){0,61}([a-z]|[0-9]))?(\\.([a-z]|[0-9])(((([a-z]|[0-9])|-)){0,61}([a-z]|[0-9]))?)+#(([a-z]|[0-9]))+((\\.|-)(([a-z]|[0-9]))+)*)\\$(([a-zA-Z]{2,3}(-[a-zA-Z]{3}(-[a-zA-Z]{3}){0,2})?|[a-zA-Z]{4,8})(-[a-zA-Z]{4})?(-([a-zA-Z]{2}|[0-9]{3}))?(-(([a-zA-Z0-9]){5,8}|[0-9]([a-zA-Z0-9]){3}))*(-[0-9A-WY-Za-wy-z](-([a-zA-Z0-9]){2,8})+)*(-[xX](-([a-zA-Z0-9]){2,8})+)?|[xX](-([a-zA-Z0-9]){2,8})+|i-default|i-mingo)))+))?$",
      "type": "string"
    },
    "key": {
      "title": "Key",
      "description": "A short, non-empty string identifier for the object. Keys must start with an alphanumeric, contain only alphanumerics and `_`, and end with an alphanumeric.(`T*` is explicitly grandfathered in as a valid key, but should not be used for new objects.)",
      "examples": [
        "E",
        "A",
        "SI",
        "L",
        "M",
        "H",
        "Mixed_case_OK",
        "alph4num3ric"
      ],
      "minLength": 1,
      "pattern": "^(([a-zA-Z0-9])|([a-zA-Z0-9][a-zA-Z0-9_]*[a-zA-Z0-9])|(T\\*))$",
      "type": "string"
    },
    "version": {
      "title": "Version",
      "default": "0.0.1",
      "description": "The version of the SSVC object. This must be a valid semantic version string.",
      "examples": [
        "1.0.0",
        "2.1.3"
      ],
      "minLength": 5,
      "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$",
      "type": "string"
    },
    "name": {
      "title": "Name",
      "minLength": 1,
      "type": "string"
    },
    "definition": {
      "title": "Definition",
      "minLength": 1,
      "type": "string"
    },
    "schemaVersion": {
      "title": "Schemaversion",
      "const": "2.0.0",
      "type": "string"
    },
    "values": {
      "title": "Values",
      "items": {
        "$ref": "#/$defs/DecisionPointValue"
      },
      "type": "array"
    }
  },
  "required": [
    "namespace",
    "key",
    "name",
    "definition",
    "schemaVersion",
    "values"
  ]
}

=== CERTCC/SSVC/data/json/decision_points/cvss/availability_impact_to_the_vulnerable_system_3_0_0.json
{
  "namespace": "cvss",
  "key": "VA",
  "version": "3.0.0",
  "name": "Availability Impact to the Vulnerable System",
  "definition": "This metric measures the impact to the availability of the impacted system resulting from a successfully exploited vulnerability.",
  "schemaVersion": "2.0.0",
  "values": [
    {
      "key": "N",
      "name": "None",
      "definition": "There is no impact to availability within the Vulnerable System."
    },
    {
      "key": "L",
      "name": "Low",
      "definition": "There is reduced performance or interruptions in resource availability. Even if repeated exploitation of the vulnerability is possible, the attacker does not have the ability to completely deny service to legitimate users. The resources in the Vulnerable System are either partially available all of the time, or fully available only some of the time, but overall there is no direct, serious consequence to the Vulnerable System."
    },
    {
      "key": "H",
      "name": "High",
      "definition": "There is total loss of availability, resulting in the attacker being able to fully deny access to resources in the impacted component; this loss is either sustained (while the attacker continues to deliver the attack) or persistent (the condition persists even after the attack has completed)."
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/aivss/verification_capability_1_0_0.json
{
  "namespace": "aivss",
  "key": "VC",
  "version": "1.0.0",
  "name": "Verification Capability",
  "definition": "Indicates whether the systemâ€™s critical properties can be formally or practically verified.",
  "schemaVersion": "2.0.0",
  "values": [
    {
      "key": "P",
      "name": "Provable",
      "definition": "Critical safety or correctness invariants can be verified."
    },
    {
      "key": "K",
      "name": "Key Invariants Verifiable",
      "definition": "Some critical properties can be verified, but not all."
    },
    {
      "key": "U",
      "name": "Unverifiable",
      "definition": "Cannot prove correctness or invariants in practice."
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/cvss/modified_availability_impact_2_0_0.json
{
  "namespace": "cvss",
  "key": "MA",
  "version": "2.0.0",
  "name": "Modified Availability Impact",
  "definition": "This metric measures the impact to availability of a successfully exploited vulnerability.",
  "schemaVersion": "2.0.0",
  "values": [
    {
      "key": "N",
      "name": "None",
      "definition": "There is no impact to the availability of the system."
    },
    {
      "key": "L",
      "name": "Low",
      "definition": "There is reduced performance or interruptions in resource availability."
    },
    {
      "key": "H",
      "name": "High",
      "definition": "There is total loss of availability, resulting in the attacker being able to fully deny access to resources in the impacted component; this loss is either sustained (while the attacker continues to deliver the attack) or persistent (the condition persists even after the attack has completed)."
    },
    {
      "key": "X",
      "name": "Not Defined",
      "definition": "This metric value is not defined. See CVSS documentation for details."
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/cvss/collateral_damage_potential_2_0_0.json
{
  "namespace": "cvss",
  "key": "CDP",
  "version": "2.0.0",
  "name": "Collateral Damage Potential",
  "definition": "This metric measures the potential for loss of life or physical assets.",
  "schemaVersion": "2.0.0",
  "values": [
    {
      "key": "N",
      "name": "None",
      "definition": "There is no potential for loss of life, physical assets, productivity or revenue."
    },
    {
      "key": "LM",
      "name": "Low-Medium",
      "definition": "A successful exploit of this vulnerability may result in moderate physical or property damage or loss."
    },
    {
      "key": "MH",
      "name": "Medium-High",
      "definition": "A successful exploit of this vulnerability may result in significant physical or property damage or loss."
    },
    {
      "key": "H",
      "name": "High",
      "definition": "A successful exploit of this vulnerability may result in catastrophic physical or property damage and loss. The range of effect may be over a wide area."
    },
    {
      "key": "ND",
      "name": "Not Defined",
      "definition": "This metric value is not defined. See CVSS documentation for details."
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/cvss/report_confidence_2_0_0.json
{
  "namespace": "cvss",
  "key": "RC",
  "version": "2.0.0",
  "name": "Report Confidence",
  "definition": "This metric measures the degree of confidence in the existence of the vulnerability and the credibility of the known technical details.",
  "schemaVersion": "2.0.0",
  "values": [
    {
      "key": "U",
      "name": "Unknown",
      "definition": "There are reports of impacts that indicate a vulnerability is present. The reports indicate that the cause of the vulnerability is unknown, or reports may differ on the cause or impacts of the vulnerability. Reporters are uncertain of the true nature of the vulnerability, and there is little confidence in the validity of the reports or whether a static Base score can be applied given the differences described."
    },
    {
      "key": "R",
      "name": "Reasonable",
      "definition": "Significant details are published, but researchers either do not have full confidence in the root cause, or do not have access to source code to fully confirm all of the interactions that may lead to the result. Reasonable confidence exists, however, that the bug is reproducible and at least one impact is able to be verified (proof-of-concept exploits may provide this)."
    },
    {
      "key": "C",
      "name": "Confirmed",
      "definition": "Detailed reports exist, or functional reproduction is possible (functional exploits may provide this). Source code is available to independently verify the assertions of the research, or the author or vendor of the affected code has confirmed the presence of the vulnerability."
    },
    {
      "key": "X",
      "name": "Not Defined",
      "definition": "This metric value is not defined. See CVSS documentation for details."
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/cvss/exploitability_1_1_0.json
{
  "namespace": "cvss",
  "key": "E",
  "version": "1.1.0",
  "name": "Exploitability",
  "definition": "This metric measures the current state of exploit technique or code availability and suggests a likelihood of exploitation.",
  "schemaVersion": "2.0.0",
  "values": [
    {
      "key": "U",
      "name": "Unproven",
      "definition": "No exploit code is yet available or an exploit method is entirely theoretical."
    },
    {
      "key": "P",
      "name": "Proof of Concept",
      "definition": "Proof of concept exploit code or an attack demonstration that is not practically applicable to deployed systems is available. The code or technique is not functional in all situations and may require substantial hand tuning by a skilled attacker for use against deployed systems."
    },
    {
      "key": "F",
      "name": "Functional",
      "definition": "Functional exploit code is available. The code works in most situations where the vulnerability is exploitable."
    },
    {
      "key": "H",
      "name": "High",
      "definition": "Either the vulnerability is exploitable by functional mobile autonomous code or no exploit is required (manual trigger) and the details for the manual technique are widely available. The code works in every situation where the vulnerability is exploitable and/or is actively being delivered via a mobile autonomous agent (a worm or virus)."
    },
    {
      "key": "ND",
      "name": "Not Defined",
      "definition": "This metric value is not defined. See CVSS documentation for details."
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/cvss/availability_requirement_1_1_0.json
{
  "namespace": "cvss",
  "key": "AR",
  "version": "1.1.0",
  "name": "Availability Requirement",
  "definition": "This metric measures the impact to the availability of a successfully exploited vulnerability.",
  "schemaVersion": "2.0.0",
  "values": [
    {
      "key": "L",
      "name": "Low",
      "definition": "Loss of availability is likely to have only a limited adverse effect on the organization or individuals associated with the organization (e.g., employees, customers)."
    },
    {
      "key": "M",
      "name": "Medium",
      "definition": "Loss of availability is likely to have a serious adverse effect on the organization or individuals associated with the organization (e.g., employees, customers)."
    },
    {
      "key": "H",
      "name": "High",
      "definition": "Loss of availability is likely to have a catastrophic adverse effect on the organization or individuals associated with the organization (e.g., employees, customers)."
    },
    {
      "key": "X",
      "name": "Not Defined",
      "definition": "This metric value is not defined. See CVSS documentation for details."
    }
  ]
}

=== CERTCC/SSVC/data/json/decision_points/cisa/asset_exposure_1_0_0.json
{
  "namespace": "cisa",
  "key": "AE",
  "version": "1.0.0",
  "name": "Asset Exposure",
  "definition": "Denotes whether the asset is accessible to unauthenticated or untrusted entities via public networks.",
  "schemaVersion": "2.0.0",
  "values": [
    {
      "key": "N",
      "name": "No",
      "definition": "The asset is NOT accessible to unauthenticated or untrusted entities via public networks."
    },
    {
      "key": "Y",
      "name": "Yes",
      "definition": "The asset is accessible to unauthenticated or untrusted entities via public networks, regardless of its physical or logical location."
    }
  ]
}
